# Generated by Django 4.2.7 on 2023-11-25 18:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news_app', '0002_alter_newsmodel_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsModel',
            new_name='News',
        ),
    ]
