# Generated by Django 4.2.7 on 2023-11-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_rename_newsmodel_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
    ]
