# Generated by Django 4.2.7 on 2023-12-03 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_recommendedvideos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecommendedVideos',
            new_name='RecommendedVideo',
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
    ]
