# Generated by Django 4.2.7 on 2024-01-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0006_news_created_at_news_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author_display_name',
            field=models.CharField(default='author name', max_length=50),
            preserve_default=False,
        ),
    ]
